### ISSUE TITLE
show user output of birdseye when birdseye is loading

### ISSUE THREAD

**Issue by Almenon** [Almenon/birdseye-vscode#12]
When birdseye starts it outputs:

* restarting with stat
* Debugger is active!
* Debugger PIN: XXX-XXX-XXX
* Running on http://127.0.0.1:port (Press CTRL+C to quit)

The "restarting with stat" command happens ~3 seconds into the start sequence.  By showing the user the start sequence they would be able to see that birdseye is starting properly instead of worrying that it is hung up.

**Comment by alexmojaki** [comment]
I'll disable the auto-reloader, that'll reduce the time drastically. Then only the 'Running on...' message shows.

**Comment by alexmojaki** [comment]
It's a feature of Flask that automatically reloads the server when it detects a change in the code. It's great for development because I don't have to manually restart any time I change the code. But there's no point for users. It's just on because it's on by default when debug mode is on (which I want to stay on) and until now I haven't had a reason to turn it off.

**Comment by alexmojaki** [comment]
I disabled the auto-reloader in the recent release, so upgrade and test.

**Comment by Almenon** [comment]
yep its faster now. Not much reason to do this feature anymore.
